### PR TITLE
Setting screen UI

### PR DESCRIPTION
**Pull request by Mina-Wael**

### CODE REVIEW

**Comment by MohabElziny** [comment]
resolve conflict and before push use this command to ignore misc.xml file : git rm --cached -r .idea/misc.xml then push

**Comment by MohabElziny** [comment]
resolve conflict and before push use this command to ignore misc.xml file : git rm --cached -r .idea/misc.xml then push

**Comment by MohabElziny** [comment]
resolve conflict and before push use this command to ignore misc.xml file : git rm --cached -r .idea/misc.xml then push

**Comment by Mina-Wael** [comment]
settings

**Pull request merged**
